// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://wvirtircujosrxsbeeyh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aXJ0aXJjdWpvc3J4c2JlZXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0NjE4ODMsImV4cCI6MjA0NzAzNzg4M30.QOZBLVelKCvb8PJG_deCI7Bh3tWj9yN0crXM8fH1cwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);